const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..');let browser,server;
const families={instrument:'CM Instrument Sans',geist:'CM Geist'};
const metrics=nodes=>nodes.map(n=>{const s=getComputedStyle(n);return Object.fromEntries(['fontSize','fontWeight','lineHeight','letterSpacing','marginTop','marginRight','marginBottom','marginLeft','paddingTop','paddingRight','paddingBottom','paddingLeft','width','maxWidth'].map(k=>[k,s[k]]))});
async function switchFont(page,font){await page.locator('.type-review select').selectOption(font);await page.waitForFunction(font=>font==='current'?!document.documentElement.dataset.typeReview:document.documentElement.dataset.typeReview===font,font);await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(300);}
async function open(page,name){await page.evaluate(name=>window.SiteViews.openSection(name),name);await page.waitForTimeout(1150);}
(async()=>{
 server=http.createServer((req,res)=>{if(req.url==='/favicon.ico'){res.writeHead(204);res.end();return;}const target=path.resolve(root,'.'+decodeURIComponent(new URL(req.url,'http://local').pathname));if(target!==root&&!target.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}fs.readFile(target===root?path.join(root,'index.html'):target,(e,b)=>{if(e){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.webp':'image/webp'})[path.extname(target)]||'application/octet-stream');res.end(b);});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port+'/';
 browser=await chromium.launch({channel:'msedge',headless:true});const errors=[];
 const page=await browser.newPage({viewport:{width:1280,height:720}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url())});
 await page.goto(base+'index.html#home');await page.waitForFunction(()=>document.fonts.check('400 12px "CM Instrument Sans"')&&document.fonts.check('400 12px "CM Geist"'));await page.waitForTimeout(600);
 assert.equal(await page.locator('.type-review').count(),1);assert.equal(await page.locator('body').evaluate(n=>getComputedStyle(n).fontFamily),'"Times New Roman", Times, Georgia, serif');
 const baseline=await page.locator('.home-index a').evaluateAll(metrics);
 assert.equal(baseline[0].fontSize,'13.84px');
 assert.equal(await page.locator('.header-tools button').first().evaluate(n=>getComputedStyle(n).fontSize),'10.56px');
 assert.equal(await page.locator('.home-footer').evaluate(n=>getComputedStyle(n).fontSize),'10.56px');
 for(const font of ['current','instrument','geist']){await switchFont(page,font);assert.deepEqual(await page.locator('.home-index a').evaluateAll(metrics),baseline);if(font!=='current')assert((await page.locator('.home-index a').first().evaluate(n=>getComputedStyle(n).fontFamily)).includes(families[font]));}
 for(const [section,selectors] of [['projects','.project-facts dt, .project-facts dd'],['work','.timeline h2, .timeline .secondary'],['about','.profile-list dt, .intro'],['log','.log-caption, .log-caption-sub']]){
   await switchFont(page,'current');await open(page,section);const reference=await page.locator(selectors).evaluateAll(metrics);
   assert.equal(reference[0].fontSize,({projects:'12.72px',work:'13.52px',about:'13.12px',log:'9.8px'})[section]);
   for(const font of ['instrument','geist','current']){await switchFont(page,font);assert.deepEqual(await page.locator(selectors).evaluateAll(metrics),reference);if(font!=='current'){assert(await page.locator(selectors).evaluateAll((ns,f)=>ns.every(n=>getComputedStyle(n).fontFamily.includes(f)),families[font]));assert(await page.locator('.language-button, .view-close, .section-identifier button').evaluateAll((ns,f)=>ns.every(n=>getComputedStyle(n).fontFamily.includes(f)),families[font]));}
     if(section==='projects')assert.equal(await page.locator('.project-row').count(),10);
     if(section==='log'){assert.equal(await page.locator('.log-plate').count(),51);assert.equal(await page.locator('.log-plate-number').first().evaluate(n=>getComputedStyle(n).fontFamily),'monospace');}
   }
 }
 console.log('PASS all three families: navigation, PROJECTS, WORK, ABOUT, LOG and controls; sizes/weights/line heights/tracking/spacing unchanged; LOG monospace retained');
 await switchFont(page,'instrument');await page.reload();await page.waitForSelector('.section-view.is-visible');assert.equal(await page.locator('.type-review select').inputValue(),'instrument');
 const cdp=await page.context().newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');const dom=await cdp.send('DOM.getDocument');const node=await cdp.send('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'.log-caption'});const used=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});assert(used.fonts.some(f=>f.isCustomFont&&f.familyName.includes('Instrument')),'Downloaded font renders actual glyphs');
 await switchFont(page,'geist'); // LOG rebuild replaces the node; inspect a stable control instead.
 const control=await cdp.send('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'.language-button'});const usedGeist=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:control.nodeId});assert(usedGeist.fonts.some(f=>f.isCustomFont&&f.familyName.includes('Geist')));
 await page.locator('.type-review select').focus();await page.keyboard.press('m');assert.equal(await page.evaluate(()=>window.SiteViews.currentView),'log');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.SiteViews.currentView),'log');await page.locator('.log-viewport').focus();await page.keyboard.press('Escape');await page.waitForTimeout(600);assert(!await page.evaluate(()=>window.SiteViews.isOpen()));await page.keyboard.press('3');await page.waitForTimeout(600);assert.equal(await page.evaluate(()=>window.SiteViews.currentView),'projects');
 console.log('PASS persistence, actual Instrument/Geist glyph rendering, selector keys isolated and existing shortcuts preserved');
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));mobile.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await mobile.goto(base+'index.html#projects');await mobile.waitForSelector('.type-review select');
 for(const font of ['current','instrument','geist']){await switchFont(mobile,font);for(const section of ['projects','work','about','log']){await open(mobile,section);assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const overlap=await mobile.evaluate(()=>{const r=document.querySelector('.type-review').getBoundingClientRect();return [...document.querySelectorAll('.header-tools button,.view-close')].some(n=>{const b=n.getBoundingClientRect();return r.left<b.right&&r.right>b.left&&r.top<b.bottom&&r.bottom>b.top})});assert(!overlap);}}
 await mobile.close();console.log('PASS mobile across all fonts and four sections: no horizontal overflow or control overlap');
 const narrow=await browser.newPage({viewport:{width:320,height:740},isMobile:true,hasTouch:true});await narrow.goto(base+'index.html#home');await narrow.waitForSelector('.type-review select');
 for(const font of ['current','instrument','geist']){await switchFont(narrow,font);assert.equal(await narrow.locator('.home-index a').first().evaluate(n=>getComputedStyle(n).fontSize),'12.8px');for(const section of ['projects','work','about','log']){await open(narrow,section);assert(await narrow.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await narrow.evaluate(()=>window.SiteI18n.setLanguage('de'));await narrow.waitForTimeout(300);assert(await narrow.evaluate(()=>{const title=document.querySelector('.section-identifier').getBoundingClientRect(),tools=document.querySelector('.section-view > .header-tools').getBoundingClientRect();return title.right<=tools.left}));}await narrow.evaluate(()=>window.SiteI18n.setLanguage('en'));}await narrow.close();
 console.log('PASS 320px mobile across three families, including German titles: readable scale, no header overlap or horizontal overflow');
 const direct=await browser.newPage();for(const entry of ['index.html',...fs.readdirSync(path.join(root,'pages')).filter(p=>p.endsWith('.html')).map(p=>'pages/'+p)]){await direct.goto(pathToFileURL(path.join(root,entry)).href);await direct.waitForSelector('.type-review select');}await direct.close();
 const production=await browser.newPage();await production.addInitScript(()=>localStorage.setItem('carlos-moya-type-review','geist'));const fontRequests=[];production.on('request',r=>{if(/typography-review|\.woff2/.test(r.url()))fontRequests.push(r.url())});
 await production.route('https://portfolio.example/**',route=>{const pathname=new URL(route.request().url()).pathname;const file=path.join(root,pathname==='/'?'index.html':pathname);route.fulfill({path:file,contentType:({'.html':'text/html','.js':'text/javascript','.css':'text/css','.webp':'image/webp'})[path.extname(file)]||'application/octet-stream'});});await production.goto('https://portfolio.example/');assert.equal(await production.locator('.type-review').count(),0);assert.equal(await production.locator('html').getAttribute('data-type-review'),null);assert(fontRequests.every(u=>u.endsWith('/scripts/typography-review.js')));await production.close();
 assert.deepEqual(errors,[]);console.log('PASS ten local HTML entry points; production gate ignores saved preference and requests no font/CSS; no console/resource errors');
 await browser.close();await new Promise(r=>server.close(r));
})().catch(async e=>{console.error(e);if(browser)await browser.close();if(server)server.close();process.exitCode=1});
